# Generated by Django 6.0.4 on 2026-04-09 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estacoes', to='desgaste.linha')),
            ],
        ),
        migrations.CreateModel(
            name='PontoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=150)),
                ('tipo_ponto', models.CharField(choices=[('patio', 'Pátio'), ('estacao', 'Estação'), ('amv', 'AMV'), ('aparelho_dilatador', 'Aparelho Dilatador'), ('estacionamento_auxiliar', 'Estacionamento Auxiliar'), ('terminal', 'Terminal'), ('acesso', 'Acesso'), ('outro', 'Outro')], max_length=30)),
                ('ordem', models.PositiveIntegerField()),
                ('posicao', models.CharField(choices=[('leste', 'Leste'), ('oeste', 'Oeste'), ('centro', 'Centro'), ('nao_aplicavel', 'Não aplicável')], default='nao_aplicavel', max_length=20)),
                ('possui_acesso_patio', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('estacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pontos_operacionais', to='desgaste.estacao')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('codigo', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='Trilho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(choices=[('1', 'Via 01'), ('2', 'Via 02')], max_length=1)),
                ('lado_trilho', models.CharField(choices=[('A', 'Trilho A'), ('B', 'Trilho B'), ('C', 'Trilho C'), ('D', 'Trilho D')], max_length=1)),
                ('ponto_kilometrico', models.CharField(blank=True, max_length=30, null=True)),
                ('marco_topografico', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_trilho', models.CharField(blank=True, max_length=100, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('data_instalacao', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('ponto_operacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trilhos', to='desgaste.pontooperacional')),
            ],
            options={
                'unique_together': {('ponto_operacional', 'via', 'lado_trilho')},
            },
        ),
    ]
