# Generated by Django 6.0.4 on 2026-04-10 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inspecao', models.DateField()),
                ('hora_inspecao', models.TimeField()),
                ('inspetor', models.CharField(max_length=100)),
                ('tipo_inspecao', models.CharField(choices=[('rotina', 'Rotina'), ('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('extraordinaria', 'Extraordinária')], default='rotina', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('trilho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecoes', to='desgaste.trilho')),
            ],
            options={
                'ordering': ['-data_inspecao', '-hora_inspecao'],
            },
        ),
    ]
