# Generated by Django 6.0.4 on 2026-04-10 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0002_inspecao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicaoDesgaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desgaste_vertical_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('desgaste_lateral_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('observacao_tecnica', models.TextField(blank=True, null=True)),
                ('status_desgaste', models.CharField(choices=[('normal', 'Normal'), ('atencao', 'Atenção'), ('critico', 'Crítico')], default='normal', max_length=20)),
                ('inspecao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicao', to='desgaste.inspecao')),
            ],
            options={
                'verbose_name': 'Medição de Desgaste',
                'verbose_name_plural': 'Medições de Desgaste',
            },
        ),
    ]
