# Generated by Django 6.0.4 on 2026-04-10 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0003_medicaodesgaste'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaixaLocalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(choices=[('1', 'Via 01'), ('2', 'Via 02')], max_length=1)),
                ('mt_inicial', models.CharField(blank=True, max_length=30, null=True)),
                ('ponto_kilometrico_inicial', models.CharField(blank=True, max_length=30, null=True)),
                ('mt_final', models.CharField(blank=True, max_length=30, null=True)),
                ('ponto_kilometrico_final', models.CharField(blank=True, max_length=30, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('ponto_operacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas_localizacao', to='desgaste.pontooperacional')),
            ],
            options={
                'verbose_name': 'Faixa de Localização',
                'verbose_name_plural': 'Faixas de Localização',
                'unique_together': {('ponto_operacional', 'via')},
            },
        ),
    ]
