# Generated by Django 6.0.4 on 2026-04-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0004_faixalocalizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenciaLinearPKMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(choices=[('1', 'Via 01'), ('2', 'Via 02')], max_length=1)),
                ('marco_topografico', models.CharField(max_length=30)),
                ('ponto_kilometrico', models.CharField(max_length=30)),
                ('local_excel', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Referência Linear PK/MT',
                'verbose_name_plural': 'Referências Lineares PK/MT',
                'ordering': ['via', 'marco_topografico'],
            },
        ),
    ]
