# Generated by Django 5.2.7 on 2026-04-23 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0006_alter_estacao_id_alter_faixalocalizacao_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspecaoTrecho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inspecao', models.DateField()),
                ('hora_inspecao', models.TimeField()),
                ('via', models.CharField(blank=True, choices=[('VIA_01', 'Via 01'), ('VIA_02', 'Via 02')], max_length=10)),
                ('trilho', models.CharField(blank=True, choices=[('A', 'Trilho A'), ('B', 'Trilho B'), ('C', 'Trilho C'), ('D', 'Trilho D')], max_length=1)),
                ('estacao_referencia', models.CharField(blank=True, max_length=80)),
                ('referencia_local', models.CharField(blank=True, max_length=120)),
                ('pk_inicial', models.CharField(blank=True, max_length=20)),
                ('pk_final', models.CharField(blank=True, max_length=20)),
                ('mt_inicial', models.CharField(blank=True, max_length=20)),
                ('mt_final', models.CharField(blank=True, max_length=20)),
                ('responsavel', models.CharField(max_length=120)),
                ('observacoes_gerais', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inspeção de trecho',
                'verbose_name_plural': 'Inspeções de trecho',
                'ordering': ['-data_inspecao', '-hora_inspecao'],
            },
        ),
        migrations.CreateModel(
            name='ItemInspecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Item de inspeção',
                'verbose_name_plural': 'Itens de inspeção',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SetorInspecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('trecho', 'Trecho'), ('patio', 'Pátio')], max_length=10)),
                ('ordem', models.PositiveIntegerField(unique=True)),
                ('limite_inicial', models.CharField(blank=True, max_length=30)),
                ('limite_final', models.CharField(blank=True, max_length=30)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Setor de inspeção',
                'verbose_name_plural': 'Setores de inspeção',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaInspecaoTrecho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criticidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('observacao', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='inspecoes/ocorrencias/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('inspecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='desgaste.inspecaotrecho')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='desgaste.iteminspecao')),
            ],
            options={
                'verbose_name': 'Ocorrência da inspeção de trecho',
                'verbose_name_plural': 'Ocorrências da inspeção de trecho',
            },
        ),
        migrations.AddField(
            model_name='inspecaotrecho',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecoes', to='desgaste.setorinspecao'),
        ),
    ]
