# Generated by Django 5.2.7 on 2026-04-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0007_inspecaotrecho_iteminspecao_setorinspecao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrocaTrilho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_troca', models.DateField()),
                ('hora_troca', models.TimeField()),
                ('via', models.CharField(choices=[('1', 'Via 01'), ('2', 'Via 02')], max_length=1)),
                ('trilho', models.CharField(choices=[('A', 'Trilho A'), ('B', 'Trilho B'), ('C', 'Trilho C'), ('D', 'Trilho D')], max_length=1)),
                ('estacao_referencia', models.CharField(blank=True, max_length=80)),
                ('referencia_local', models.CharField(blank=True, max_length=120)),
                ('mt_inicial', models.CharField(max_length=30)),
                ('mt_final', models.CharField(max_length=30)),
                ('tamanho_trilho_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('temperatura_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tempo_reacao_aco_seg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tempo_vazao_seg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('perfil_trilho', models.CharField(blank=True, choices=[('UIC60', 'UIC 60')], max_length=20)),
                ('classe_trilho', models.CharField(blank=True, choices=[('260', '260'), ('350', '350'), ('400', '400')], max_length=10)),
                ('tipo_solda', models.CharField(blank=True, choices=[('thermit', 'Thermit'), ('rail_tech', 'Rail Tech')], max_length=20)),
                ('motivo_troca', models.CharField(blank=True, max_length=120)),
                ('os_numero', models.CharField(blank=True, max_length=50)),
                ('responsavel', models.CharField(max_length=120)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Troca de Trilho',
                'verbose_name_plural': 'Trocas de Trilho',
                'ordering': ['-data_troca', '-hora_troca'],
            },
        ),
    ]
