# Generated by Django 5.2.7 on 2026-05-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0008_trocatrilho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trocatrilho',
            name='temperatura_c',
        ),
        migrations.RemoveField(
            model_name='trocatrilho',
            name='tempo_reacao_aco_seg',
        ),
        migrations.AddField(
            model_name='trocatrilho',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='trocas_trilho/', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='trocatrilho',
            name='temperatura_antes_solda_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura antes da solda (°C)'),
        ),
        migrations.AddField(
            model_name='trocatrilho',
            name='temperatura_depois_solda_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura depois da solda (°C)'),
        ),
        migrations.AddField(
            model_name='trocatrilho',
            name='tempo_aquecimento_seg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tempo de aquecimento (s)'),
        ),
        migrations.AlterField(
            model_name='trocatrilho',
            name='tempo_vazao_seg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tempo de vazão (s)'),
        ),
    ]
