# Generated by Django 5.2.7 on 2026-05-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0009_remove_trocatrilho_temperatura_c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trocatrilho',
            name='medida_folga_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Medida da folga (mm)'),
        ),
        migrations.AddField(
            model_name='trocatrilho',
            name='solda_fechamento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Solda de fechamento?'),
        ),
        migrations.AddField(
            model_name='trocatrilho',
            name='trilho_transicao',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Trilho de transição?'),
        ),
    ]
