# Generated by Django 5.2.7 on 2026-05-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0010_trocatrilho_medida_folga_mm_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trocatrilho',
            options={'ordering': ['-data_troca', '-hora_inicio_troca', '-hora_troca'], 'verbose_name': 'Troca de Trilho', 'verbose_name_plural': 'Trocas de Trilho'},
        ),
        migrations.AddField(
            model_name='trocatrilho',
            name='hora_fim_troca',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora fim da troca'),
        ),
        migrations.AddField(
            model_name='trocatrilho',
            name='hora_inicio_troca',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora início da troca'),
        ),
        migrations.AlterField(
            model_name='trocatrilho',
            name='hora_troca',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora da troca'),
        ),
        migrations.AlterField(
            model_name='trocatrilho',
            name='motivo_troca',
            field=models.CharField(blank=True, choices=[('programada', 'Programada'), ('trinca', 'Trinca'), ('desgaste', 'Desgaste')], max_length=20, verbose_name='Motivo da troca'),
        ),
        migrations.AlterField(
            model_name='trocatrilho',
            name='tempo_aquecimento_seg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tempo de aquecimento (min)'),
        ),
    ]
