# Generated by Django 5.2.7 on 2026-06-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0012_inspecaotrecho_hora_fim_inspecao_alter_estacao_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciainspecaotrecho',
            name='trilho',
            field=models.CharField(blank=True, choices=[('A', 'Trilho A'), ('B', 'Trilho B'), ('C', 'Trilho C'), ('D', 'Trilho D')], max_length=1, verbose_name='Trilho da ocorrência'),
        ),
    ]
