# Generated by Django 5.2.7 on 2026-06-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0013_ocorrenciainspecaotrecho_trilho'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciainspecaotrecho',
            name='mt_problema',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='MT do problema'),
        ),
    ]
