# Generated by Django 5.2.7 on 2026-06-03 20:15

from django.db import migrations


def popular_itens_ocorrencia_completos(apps, schema_editor):
    ItemInspecao = apps.get_model("desgaste", "ItemInspecao")

    itens = [
        "ALMA DO TRILHO COM DEFEITO",
        "ALMOFADA DANIFICADA",
        "ALMOFADA DESLOCADA",
        "ALMOFADA AUSENTE",
        "APARELHO DILATADOR COM ANOMALIA",
        "APARELHO DILATADOR COM FOLGA",
        "APARELHO DILATADOR COM OBSTRUÇÃO",
        "BARRA DE JUNÇÃO DANIFICADA",
        "BARRA DE JUNÇÃO FROUXA",
        "BARRA DE JUNÇÃO AUSENTE",
        "BOLETO DO TRILHO COM DESGASTE",
        "BOLETO DO TRILHO COM MARCA",
        "BOLETO DO TRILHO COM REBARBA",
        "CHUMBADOR DANIFICADO",
        "CHUMBADOR FROUXO",
        "CHUMBADOR AUSENTE",
        "CONTRA TRILHO COM ANOMALIA",
        "CONTRA TRILHO COM FOLGA",
        "DORMENTE DANIFICADO",
        "DORMENTE TRINCADO",
        "DORMENTE QUEBRADO",
        "DORMENTE DESALINHADO",
        "DORMENTE COM DESGASTE",
        "DRENAGEM OBSTRUÍDA",
        "FIXAÇÃO DANIFICADA",
        "FIXAÇÃO SOLTA",
        "FIXAÇÃO AUSENTE",
        "FIXAÇÃO DESLOCADA",
        "FIXAÇÃO COM DESGASTE",
        "GRAMPO DANIFICADO",
        "GRAMPO SOLTO",
        "GRAMPO AUSENTE",
        "INTERFERÊNCIA NA VIA",
        "JACARÉ COM DESGASTE",
        "JACARÉ COM TRINCA",
        "JUNTA COMPROMETIDA",
        "JUNTA COM FOLGA",
        "JUNTA COM DESNÍVEL",
        "LASTRO CONTAMINADO",
        "LASTRO INSUFICIENTE",
        "LASTRO IRREGULAR",
        "LASTRO DESLOCADO",
        "LIMPEZA NECESSÁRIA",
        "OBJETO NA VIA",
        "PARAFUSO AUSENTE",
        "PARAFUSO FROUXO",
        "PARAFUSO DANIFICADO",
        "PONTA DE AGULHA COM ANOMALIA",
        "PONTA DE AGULHA COM DESGASTE",
        "PONTA DE AGULHA COM FOLGA",
        "RETENSOR DANIFICADO",
        "RETENSOR SOLTO",
        "RETENSOR AUSENTE",
        "SAPATA DANIFICADA",
        "SAPATA DESLOCADA",
        "SOLDA COM ANOMALIA",
        "SOLDA COM TRINCA",
        "SOLDA COM REBARBA",
        "SOLDA COM DESNÍVEL",
        "TALA DANIFICADA",
        "TALA FROUXA",
        "TALA AUSENTE",
        "TIREFÃO AUSENTE",
        "TIREFÃO FROUXO",
        "TIREFÃO DANIFICADO",
        "TRILHO COM DESGASTE",
        "TRILHO COM TRINCA",
        "TRILHO COM FRATURA",
        "TRILHO COM DESNÍVEL",
        "TRILHO COM EMPENO",
        "TRILHO COM CORROSÃO",
        "TRILHO COM REBARBA",
        "TRILHO MARCADO",
        "VIA COM DESALINHAMENTO",
        "VIA COM DESNIVELAMENTO",
        "VIA COM SUJIDADE",
        "OUTROS",
    ]

    for nome in itens:
        ItemInspecao.objects.update_or_create(
            nome=nome,
            defaults={"ativo": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("desgaste", "0015_popular_setores_itens_iniciais"),
    ]

    operations = [
        migrations.RunPython(
            popular_itens_ocorrencia_completos,
            migrations.RunPython.noop,
        ),
    ]