# Generated by Django 5.2.7 on 2026-06-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0018_padronizar_via_inspecaotrecho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lubrificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('via', models.CharField(blank=True, choices=[('1', 'Via 01'), ('2', 'Via 02')], max_length=1)),
                ('mt', models.CharField(blank=True, max_length=30)),
                ('status_operacional', models.CharField(choices=[('OPERANTE', 'Operante'), ('INOPERANTE', 'Inoperante'), ('MANUTENCAO', 'Em manutenção')], default='OPERANTE', max_length=20)),
            ],
            options={
                'verbose_name': 'Lubrificador',
                'verbose_name_plural': 'Lubrificadores',
            },
        ),
    ]
