# Generated by Django 5.2.7 on 2026-06-23 04:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0020_populate_lubrificadores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lubrificador',
            options={'ordering': ['nome'], 'verbose_name': 'Lubrificador', 'verbose_name_plural': 'Lubrificadores'},
        ),
        migrations.AlterField(
            model_name='lubrificador',
            name='status_operacional',
            field=models.CharField(choices=[('OPERANTE', 'Operante'), ('OPERANTE_RESTRICAO', 'Operante com restrição'), ('MANUTENCAO', 'Em manutenção'), ('INOPERANTE', 'Inoperante')], default='OPERANTE', max_length=30),
        ),
        migrations.CreateModel(
            name='RegistroLubrificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e hora da inspeção')),
                ('status_operacional', models.CharField(choices=[('OPERANTE', 'Operante'), ('OPERANTE_RESTRICAO', 'Operante com restrição'), ('MANUTENCAO', 'Em manutenção'), ('INOPERANTE', 'Inoperante')], max_length=30, verbose_name='Status operacional')),
                ('nivel_graxa_percentual', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nível de graxa (%)')),
                ('alimentacao_eletrica', models.CharField(choices=[('NORMAL', 'Normal'), ('AUSENTE', 'Ausente'), ('INSTAVEL', 'Instável'), ('NAO_VERIFICADA', 'Não verificada')], max_length=20, verbose_name='Alimentação elétrica')),
                ('tensao_alimentacao', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tensão de alimentação (V)')),
                ('controladora', models.CharField(choices=[('LIGADA', 'Ligada'), ('DESLIGADA', 'Desligada'), ('COM_FALHA', 'Com falha'), ('NAO_VERIFICADA', 'Não verificada')], max_length=20, verbose_name='Controladora')),
                ('motor', models.CharField(choices=[('FUNCIONANDO', 'Ligado e funcionando'), ('DESLIGADO', 'Desligado'), ('TRAVADO', 'Travado'), ('FUNCIONAMENTO_IRREGULAR', 'Funcionamento irregular'), ('NAO_VERIFICADO', 'Não verificado')], max_length=30, verbose_name='Motor')),
                ('integridade_regua', models.CharField(choices=[('INTEGRA', 'Íntegra'), ('DANIFICADA', 'Danificada'), ('ENTUPIDA', 'Entupida'), ('COM_VAZAMENTO', 'Com vazamento'), ('NAO_VERIFICADA', 'Não verificada')], max_length=20, verbose_name='Condição da régua')),
                ('quantidade_total_bicos', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quantidade total de bicos')),
                ('quantidade_bicos_funcionais', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quantidade de bicos funcionais')),
                ('sensor_inducao', models.CharField(choices=[('FUNCIONANDO', 'Funcionando'), ('NAO_DETECTA', 'Não detecta'), ('INTERMITENTE', 'Funcionamento intermitente'), ('DESALINHADO', 'Desalinhado'), ('NAO_TESTADO', 'Não testado')], max_length=20, verbose_name='Sensor de indução')),
                ('falha_encontrada', models.TextField(blank=True, verbose_name='Falha ou condição encontrada')),
                ('servico_executado', models.TextField(blank=True, verbose_name='Serviço executado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('lubrificador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='desgaste.lubrificador')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_lubrificadores', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Registro de lubrificador',
                'verbose_name_plural': 'Registros de lubrificadores',
                'ordering': ['-data_hora', '-criado_em'],
            },
        ),
    ]
