# Generated by Django 5.2.7 on 2026-06-23 09:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0021_add_registro_lubrificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrolubrificador',
            name='inspecao_origem',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_atuacao': 'INSPECAO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execucoes_corretivas', to='desgaste.registrolubrificador', verbose_name='Inspeção de origem'),
        ),
        migrations.AddField(
            model_name='registrolubrificador',
            name='resultado_corretiva',
            field=models.CharField(blank=True, choices=[('RESOLVIDA', 'Resolvida'), ('PARCIAL', 'Executada parcialmente'), ('NAO_RESOLVIDA', 'Não resolvida')], max_length=20, verbose_name='Resultado da execução corretiva'),
        ),
        migrations.AddField(
            model_name='registrolubrificador',
            name='resultado_inspecao',
            field=models.CharField(blank=True, choices=[('CONFORME', 'Conforme'), ('COM_ANOMALIA', 'Com anomalia')], max_length=20, verbose_name='Resultado da inspeção'),
        ),
        migrations.AddField(
            model_name='registrolubrificador',
            name='situacao_pendencia',
            field=models.CharField(choices=[('SEM_PENDENCIA', 'Sem pendência'), ('AGUARDANDO_CORRETIVA', 'Aguardando corretiva'), ('EM_TRATAMENTO', 'Em tratamento'), ('CONCLUIDA', 'Concluída')], default='SEM_PENDENCIA', max_length=30, verbose_name='Situação da pendência'),
        ),
        migrations.AddField(
            model_name='registrolubrificador',
            name='tipo_atuacao',
            field=models.CharField(choices=[('INSPECAO', 'Inspeção'), ('CORRETIVA', 'Execução corretiva')], default='INSPECAO', max_length=20, verbose_name='Tipo de atuação'),
        ),
        migrations.AlterField(
            model_name='registrolubrificador',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e hora da atuação'),
        ),
        migrations.AlterField(
            model_name='registrolubrificador',
            name='falha_encontrada',
            field=models.TextField(blank=True, verbose_name='Resumo das falhas'),
        ),
        migrations.CreateModel(
            name='FalhaRegistroLubrificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('ALIMENTACAO_AUSENTE', 'Alimentação elétrica ausente'), ('ALIMENTACAO_INSTAVEL', 'Alimentação elétrica instável'), ('CONTROLADORA_DESLIGADA', 'Controladora desligada'), ('CONTROLADORA_COM_FALHA', 'Controladora com falha'), ('MOTOR_DESLIGADO', 'Motor desligado'), ('MOTOR_TRAVADO', 'Motor travado'), ('MOTOR_IRREGULAR', 'Funcionamento irregular do motor'), ('REGUA_DANIFICADA', 'Régua danificada'), ('REGUA_ENTUPIDA', 'Régua entupida'), ('REGUA_COM_VAZAMENTO', 'Vazamento na régua'), ('BICOS_SEM_VAZAO', 'Bicos sem vazão'), ('SENSOR_NAO_DETECTA', 'Sensor de indução não detecta'), ('SENSOR_INTERMITENTE', 'Sensor de indução intermitente'), ('SENSOR_DESALINHADO', 'Sensor de indução desalinhado')], max_length=50, verbose_name='Falha identificada')),
                ('registro_inspecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='falhas', to='desgaste.registrolubrificador', verbose_name='Inspeção')),
            ],
            options={
                'verbose_name': 'Falha do lubrificador',
                'verbose_name_plural': 'Falhas dos lubrificadores',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='OrdemCorretivaLubrificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número da ordem corretiva')),
                ('situacao', models.CharField(choices=[('AGUARDANDO', 'Aguardando execução'), ('EM_ANDAMENTO', 'Em andamento'), ('PARCIAL', 'Executada parcialmente'), ('CONCLUIDA', 'Concluída'), ('NAO_RESOLVIDA', 'Não resolvida')], default='AGUARDANDO', max_length=30, verbose_name='Situação da ordem')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('falhas_atendidas', models.ManyToManyField(blank=True, related_name='ordens_corretivas', to='desgaste.falharegistrolubrificador', verbose_name='Falhas atendidas')),
                ('inspecao_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_corretivas', to='desgaste.registrolubrificador', verbose_name='Inspeção de origem')),
            ],
            options={
                'verbose_name': 'Ordem corretiva do lubrificador',
                'verbose_name_plural': 'Ordens corretivas dos lubrificadores',
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='registrolubrificador',
            name='ordem_corretiva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='desgaste.ordemcorretivalubrificador', verbose_name='Ordem corretiva'),
        ),
        migrations.AddConstraint(
            model_name='falharegistrolubrificador',
            constraint=models.UniqueConstraint(fields=('registro_inspecao', 'codigo'), name='falha_unica_por_inspecao_lubrificador'),
        ),
    ]
