# Generated by Django 5.2.7 on 2026-06-23 06:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0021_add_registro_lubrificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrolubrificador',
            name='inspecao_origem',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_atuacao': 'INSPECAO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corretivas', to='desgaste.registrolubrificador', verbose_name='Inspeção de origem'),
        ),
        migrations.AddField(
            model_name='registrolubrificador',
            name='resultado_corretiva',
            field=models.CharField(blank=True, choices=[('RESOLVIDA', 'Resolvida'), ('PARCIAL', 'Resolvida parcialmente'), ('NAO_RESOLVIDA', 'Não resolvida')], max_length=20, verbose_name='Resultado da corretiva'),
        ),
        migrations.AddField(
            model_name='registrolubrificador',
            name='resultado_inspecao',
            field=models.CharField(blank=True, choices=[('CONFORME', 'Conforme'), ('COM_ANOMALIA', 'Com anomalia')], max_length=20, verbose_name='Resultado da inspeção'),
        ),
        migrations.AddField(
            model_name='registrolubrificador',
            name='situacao_pendencia',
            field=models.CharField(choices=[('SEM_PENDENCIA', 'Sem pendência'), ('AGUARDANDO_CORRETIVA', 'Aguardando corretiva'), ('EM_TRATAMENTO', 'Em tratamento'), ('CONCLUIDA', 'Concluída')], default='SEM_PENDENCIA', max_length=30, verbose_name='Situação da pendência'),
        ),
        migrations.AddField(
            model_name='registrolubrificador',
            name='tipo_atuacao',
            field=models.CharField(choices=[('INSPECAO', 'Inspeção'), ('CORRETIVA', 'Manutenção corretiva')], default='INSPECAO', max_length=20, verbose_name='Tipo de atuação'),
        ),
        migrations.AlterField(
            model_name='registrolubrificador',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e hora da atuação'),
        ),
        migrations.CreateModel(
            name='OrdemCorretivaLubrificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Número da ordem corretiva')),
                ('registro_corretiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_corretivas', to='desgaste.registrolubrificador', verbose_name='Registro da corretiva')),
            ],
            options={
                'verbose_name': 'Ordem corretiva do lubrificador',
                'verbose_name_plural': 'Ordens corretivas dos lubrificadores',
                'ordering': ['numero'],
                'constraints': [models.UniqueConstraint(fields=('registro_corretiva', 'numero'), name='ordem_unica_por_corretiva_lubrificador')],
            },
        ),
    ]
