# Generated by Django 5.2.7 on 2026-06-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0022_separar_inspecao_corretiva_lubrificadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemcorretivalubrificador',
            name='situacao',
            field=models.CharField(choices=[('EXECUTADA', 'Executada'), ('PARCIAL', 'Executada parcialmente')], default='EXECUTADA', max_length=20, verbose_name='Status da ordem'),
        ),
    ]
