# Generated by Django 5.2.7 on 2026-06-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0022_estruturar_falhas_ordens_lubrificadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemcorretivalubrificador',
            name='situacao',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando execução'), ('PARCIAL', 'Executada parcialmente'), ('EXECUTADA', 'Executada')], default='AGUARDANDO', max_length=30, verbose_name='Situação da ordem'),
        ),
        migrations.AlterField(
            model_name='registrolubrificador',
            name='resultado_corretiva',
            field=models.CharField(blank=True, choices=[('EXECUTADA', 'Executada'), ('PARCIAL', 'Executada parcialmente')], max_length=20, verbose_name='Resultado da execução corretiva'),
        ),
    ]
