# Generated by Django 5.2.7 on 2026-06-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0023_adicionar_status_ordem_corretiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrolubrificador',
            name='resultado_inspecao',
            field=models.CharField(blank=True, choices=[('CONFORME', 'OK'), ('COM_ANOMALIA', 'NOK')], max_length=20, verbose_name='Resultado da inspeção'),
        ),
    ]
