# Generated by Django 5.2.7 on 2026-06-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0024_alterar_resultado_inspecao_ok_nok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lubrificador',
            name='status_operacional',
            field=models.CharField(choices=[('OPERANTE', 'Operacional'), ('OPERANTE_RESTRICAO', 'Operante com restrição'), ('MANUTENCAO', 'Em manutenção'), ('INOPERANTE', 'Inoperante')], default='OPERANTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='registrolubrificador',
            name='status_operacional',
            field=models.CharField(choices=[('OPERANTE', 'Operacional'), ('OPERANTE_RESTRICAO', 'Operante com restrição'), ('MANUTENCAO', 'Em manutenção'), ('INOPERANTE', 'Inoperante')], max_length=30, verbose_name='Status operacional'),
        ),
    ]
