# Generated by Django 5.2.7 on 2026-06-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0025_renomear_status_operacional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lubrificador',
            name='status_operacional',
            field=models.CharField(choices=[('OPERANTE', 'Operacional'), ('OPERANTE_RESTRICAO', 'Operacional com restrição'), ('MANUTENCAO', 'Manutenção'), ('INOPERANTE', 'Inoperante')], default='OPERANTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='registrolubrificador',
            name='status_operacional',
            field=models.CharField(choices=[('OPERANTE', 'Operacional'), ('OPERANTE_RESTRICAO', 'Operacional com restrição'), ('MANUTENCAO', 'Manutenção'), ('INOPERANTE', 'Inoperante')], max_length=30, verbose_name='Status operacional'),
        ),
    ]
