# Generated by Django 5.2.7 on 2026-06-23 19:50

from django.db import migrations


def limpar_dados_lubrificadores(apps, schema_editor):
    Lubrificador = apps.get_model(
        "desgaste",
        "Lubrificador",
    )
    RegistroLubrificador = apps.get_model(
        "desgaste",
        "RegistroLubrificador",
    )
    OrdemCorretivaLubrificador = apps.get_model(
        "desgaste",
        "OrdemCorretivaLubrificador",
    )

    total_lubrificadores = Lubrificador.objects.count()
    total_registros = RegistroLubrificador.objects.count()
    total_ordens = OrdemCorretivaLubrificador.objects.count()

    # As ordens dependem dos registros corretivos.
    OrdemCorretivaLubrificador.objects.all().delete()

    # As corretivas referenciam as inspeções com PROTECT,
    # portanto precisam ser removidas primeiro.
    RegistroLubrificador.objects.filter(
        tipo_atuacao="CORRETIVA"
    ).delete()

    RegistroLubrificador.objects.all().delete()

    # Mantém os 26 equipamentos e reinicia o status.
    Lubrificador.objects.all().update(
        status_operacional="OPERANTE"
    )

    print(
        "Limpeza dos lubrificadores concluída: "
        f"{total_ordens} ordens removidas, "
        f"{total_registros} registros removidos e "
        f"{total_lubrificadores} lubrificadores preservados."
    )


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0026_corrigir_nomes_status_lubrificador'),
    ]

    operations = [
        migrations.RunPython(
            limpar_dados_lubrificadores,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
