# Generated by Django 5.2.7 on 2026-06-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desgaste', '0027_limpar_dados_lubrificadores_producao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemcorretivalubrificador',
            name='falha_vinculada',
            field=models.TextField(blank=True, default='', verbose_name='Falha vinculada à ordem'),
        ),
    ]
